[package]
name = "discord-reaction-insights"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
dotenv = "0.15.0"
serenity = "0.12"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
tokio-cron-scheduler = "0.13.0"
